---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: parkr.github.io.
  - type: MX
    values:
    - exchange: aspmx.l.google.com.
      preference: 1
    - exchange: alt1.aspmx.l.google.com.
      preference: 5
    - exchange: alt2.aspmx.l.google.com.
      preference: 5
    - exchange: aspmx2.googlemail.com.
      preference: 10
    - exchange: aspmx3.googlemail.com.
      preference: 10
  - type: TXT
    value: keybase-site-verification=6YW5wF_FcU_0UFY3Gu-Hni0VeIQItJ158eyr-mydzF0
blog:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkr.github.io.
bookmarks:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkr.github.io.
email.dev:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: mailgun.org.
stuff:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
