---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: kondwani.parkermakes.tools.
  - type: TXT
    values:
      - v=spf1 -all # SPF record to block all mail
      - v=DMARC1\; p=reject\; adkim=s\; aspf=s\; # DMARC policy to block all mail
'*':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parker.codes.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parker.codes.
