---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: kondwani.parkermakes.tools.
  - type: TXT
    values:
      - keybase-site-verification=RBWd3BpdCNOUWnMZFDz_8ni5c9stWFcdtz2c7k4d5Og
      - v=spf1 -all # SPF record to block all mail
      - v=DMARC1\; p=reject\; adkim=s\; aspf=s\; # DMARC policy to block all mail
'4240':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
gifs:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkr.github.io.
gossip:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kruffudd.parkermakes.tools.
irc:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kruffudd.parkermakes.tools.
lib:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
photo:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkermoo.re.
ping:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kruffudd.parkermakes.tools.
recipes:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
webdev:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
www:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkermoo.re.
