---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: aneirin.parkermakes.tools.
  - type: MX
    value:
      exchange: mail.parkermoo.re.
      preference: 10
  - type: TXT
    value: keybase-site-verification=RBWd3BpdCNOUWnMZFDz_8ni5c9stWFcdtz2c7k4d5Og
'4240':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
gifs:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
gossip:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: aneirin.parkermakes.tools.
irc:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: gossip.parkermoo.re.
lib:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
ping:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: aneirin.parkermakes.tools.
recipes:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
webdev:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
www:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkermoo.re.
