---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: beavan.parkermakes.tools.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: beavan.parkermakes.tools.
