#!/bin/bash

set -e

if ! [ -x "vendor/bin/octodns-compare" ]; then
  script/bootstrap
fi

. script/provider-credentials

for zone in "${ZONES[@]}"; do
    echo "Processing zone $zone."
    ./vendor/bin/octodns-compare \
      --config-file config/production.yaml \
      --a cloudflare \
      --b config \
      --zone "$zone." \
      "$@"
    vendor/bin/yaml2json config/"$zone".yaml | jq -r 'keys | @sh' | xargs -n 1 -t echo
done
