#!/bin/bash

set -e
set -o pipefail

TEMPORARY_ALLOWLIST='^(radar|ping)\.'

python3 script/list-domains.py | \
  egrep '^(CNAME|ALIAS|A)' | egrep -v '10\.0\.1' | egrep -v '(baymax|delwyn)\.' | egrep -v '\.ts\.net$' | \
  awk '{print $2}' | sort | uniq | \
  egrep -v '^(imap|smtp|pop|webmail|email|\*)\.' | \
  egrep -v "$TEMPORARY_ALLOWLIST" | \
  xargs -n 1 -t -I{} \
    curl --fail --no-progress-meter --output /dev/null https://{}
