#!/bin/bash

set -e

python3 script/list-domains.py | \
  egrep '^(CNAME|ALIAS|A)' | egrep -v '10\.0\.1' | \
  awk '{print $2}' | sort | uniq | \
  egrep -v '^(imap|smtp|pop|webmail|\*)\.' | \
  xargs -n 1 -t -I{} \
    curl --fail --no-progress-meter --output /dev/null https://{}
