#!/bin/sh

ZONES=""
ZONES="${ZONES} byparker.com"
ZONES="${ZONES} keltermoore.com"
ZONES="${ZONES} parkermakes.tools"
ZONES="${ZONES} parkermoo.re"
ZONES="${ZONES} parkermoore.de"
ZONES="${ZONES} parkermoore.site"
ZONES="${ZONES} parkers.link"
ZONES="${ZONES} parkers.photos"

export DOCKER_IMAGE="parkr/octodns:v0.9.14"
export CLOUDFLARE_TOKEN="$(cat ~/.config/cloudflare/parker-token)"
export CLOUDFLARE_EMAIL="$(cat ~/.config/cloudflare/parker-email)"

octodns() {
  local subcommand="$1"
  shift
  if [ -z "$subcommand" ]; then
    echo "no octodns subcommand specified."
    exit 1
  fi
  cwd="$(pwd)"

  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_EMAIL="$CLOUDFLARE_EMAIL" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    octodns-"$subcommand" "$@"
}
