#!/bin/sh

declare -a ZONES
export ZONES=(
    byparker.com
    keltermoore.com
    parkermakes.tools
    parkermoo.re
    parkermoore.de
    parkers.photos
)

export DOCKER_IMAGE="parkr/octodns:c0730918a6abe1ba78b720b3d398c4e818d98b1a"
export CLOUDFLARE_TOKEN="$(cat ~/.config/cloudflare/parker-token)"
export CLOUDFLARE_EMAIL="$(cat ~/.config/cloudflare/parker-email)"

octodns() {
  local subcommand="$1"
  shift
  if [ -z "$subcommand" ]; then
    echo "no octodns subcommand specified."
    exit 1
  fi
  cwd="$(pwd)"

  docker run -it --rm \
    -v "$cwd":"$cwd" \
    -w "$cwd" \
    -e CLOUDFLARE_EMAIL="$CLOUDFLARE_EMAIL" \
    -e CLOUDFLARE_TOKEN="$CLOUDFLARE_TOKEN" \
    "$DOCKER_IMAGE" \
    octodns-"$subcommand" "$@"
}
