---
on: push
name: Ensure all domains resolve
jobs:
  resolve:
    name: no 404s
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: script/ensure-no-404s
      run: script/ensure-no-404s
