---
on: push
name: Ensure all domains resolve
jobs:
  resolve:
    name: no 404s
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: script/ensure-no-404s
      run: script/ensure-no-404s
